### ISSUE TITLE
add wasm to filePattern defaults?

### ISSUE THREAD

**Issue by jenweber** [ember-cli-deploy/ember-cli-deploy-s3#101]
What do you think about adding web assembly (wasm) files to the list of `filePattern` defaults? It's fairly well supported in current web browsers.

https://caniuse.com/#feat=wasm
![screen shot 2018-01-12 at 2 41 13 pm](https://user-images.githubusercontent.com/16627268/34892302-c5d3f796-f7a6-11e7-9a39-d048e38e27fd.png)

It's easy to configure `ENV['s3']` as is. However, I think this change may be worth making because when a request for WASM file fails, it throws some really obscure errors when it tries to read the resulting 404 html as wasm binary. I think it would have thrown my team for a loop if I didn't have an instinct for quirks of our deploy pipeline.

**Comment by lukemelia** [comment]
No objections here! PR away. 😄

**Comment by jenweber** [comment]
PR https://github.com/ember-cli-deploy/ember-cli-deploy-s3/pull/102

**Comment by ghedamat** [comment]
done
