### ISSUE TITLE
AWS S3 default MIME type for wasm files is incorrect

### ISSUE THREAD

**Issue by jenweber** [ember-cli-deploy/ember-cli-deploy-s3#105]
Can we bump the `mime` npm package version? The version used in this plugin (1.3.4) does not handle wasm type correctly. I could PR to go to just 1.6, the last release before a major bump, or I can try to figure out 2.x.

**The current behavior:**
With what appears to be some very recent changes in Chrome, running wasm files in S3 with MIME type `application/octet-stream` causes a problem when you run the files - an error message about incorrect MIME type and "fallback to array buffer." I've now had to set S3 MIME type to `application/wasm` by hand after deployment. It's not fatal, because the browser determines a fallback. But it's annoying and I think there's some latency.

**Goal**
Update `mime` version so that it works automatically

**Comment by ghedamat** [comment]
@jenweber I think we'll take a PR either way :)

1.6 is probably easier but I don't think we're opposed to 2.X

find us on slack if you havn't already and you need help! @achambers is probably your man for this one

**Comment by jenweber** [comment]
Sounds good - I'll see if I can get it to 2 without much pain. I imagine there will be other file formats with the same issue in the future.

**Comment by jenweber** [comment]
PR https://github.com/ember-cli-deploy/ember-cli-deploy-s3/pull/107 includes the details of what I had to change.
