### ISSUE TITLE
New tag

### ISSUE THREAD

**Issue by ghost** [ember-cli-deploy/ember-cli-deploy-s3#113]
I would like to use the `endpoint` configuration item. Is there a plan for a new tag anytime soon?

**Comment by thec0keman** [comment]
:+1:
The content-type fix for items in sub-paths would be great to get out in a new version

**Comment by lifeart** [comment]
@lukemelia any news on it? I also need `endpoint` (https://github.com/ember-cli-deploy/ember-cli-deploy-s3/pull/111/files)

**Comment by lifeart** [comment]
@ammorrise, @thec0keman  https://github.com/ember-cli-deploy/ember-cli-deploy-s3/releases/tag/v2.0.0
