### ISSUE TITLE
Using AWS from CLI

### ISSUE THREAD

**Issue by surya-narayanan** [ember-cli-deploy/ember-cli-deploy-s3#114]
Hi, I am trying to use CDK deploy from the command line and on some default python resources, from https://github.com/aws-samples/aws-cdk-examples. 

When I install the dependencies successfully and try deploying, I get the following messages. 

One possible reason is a firewall, but I'm not on one. The message is exactly

"Inaccessible host: `cloudformation.oregon.amazonaws.com'. This service may not be available in the `Oregon' region."

Any ideas how to fix this or work through it?

**Comment by achambers** [comment]
Hi. I may be missing something here but can you help me understand what this has to do with ember-cli-deploy?

**Comment by surya-narayanan** [comment]
it doesn't - sorry - I found the appropriate place to put it - new to the platform - sorry
