### ISSUE TITLE
Consider including .json files by default?

### ISSUE THREAD

**Issue by simonihmig** [ember-cli-deploy/ember-cli-deploy-s3#126]
Had to add `json` extension to `filePattern` to also deploy those files to S3. Wondering if that shouldn't work by default. Used in the wild for example for:
* `manifest.json` (PWA)
* `ember-intl` translation files (when not bundled into vendor, using `publicOnly: true` config)
* https://github.com/empress/broccoli-static-site-json
* https://github.com/adopted-ember-addons/ember-cli-ifa (mentions this S3 related issue in Readme)

**Comment by lukemelia** [comment]
I'm open to this @simonihmig
