### ISSUE TITLE
Use immutable in cache-control

### ISSUE THREAD

**Issue by BryanCrotaz** [ember-cli-deploy/ember-cli-deploy-s3#160]
Fingerprinted files are guaranteed to never change.

The `immutable` tag in the `cache-control` header was recently added so that browsers no longer need to check for a fresh file and get a 304 response.

@lukemelia  Any objections to me submitting a PR for this?

[https://www.keycdn.com/blog/cache-control-immutable](https://www.keycdn.com/blog/cache-control-immutable)

**Comment by lukemelia** [comment]
Sounds like a good improvement @BryanCrotaz. Thanks.

**Comment by lukemelia** [comment]
Closed by #161
