### ISSUE TITLE
AWS SDK v2 deprecation warning

### ISSUE THREAD

**Issue by gzurbach** [ember-cli-deploy/ember-cli-deploy-s3#173]
When building my Ember app, I am seeing this message:

```
NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
```

I looks like `ember-cli-deploy-s3` and `ember-cli-deploy-s3-index` both use `aws-sdk@2.x`. The v3 of the SDK is in a new package/repo: https://github.com/aws/aws-sdk-js-v3

I'm sure if this was something being worked on already. Is help needed for updating to v3?

**Comment by lukemelia** [comment]
Hi @gzurbach, any help you ca provide would be terrific!

**Comment by gzurbach** [comment]
Ok I will try to submit a PR. It should be pretty straightforward. 

I am adding these links as a reference/reminder for myself: 

- https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md
- https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/migrating-to-v3.html

**Comment by mattstrayer** [comment]
This might be helpful as well https://www.npmjs.com/package/aws-sdk-js-codemod @gzurbach

**Comment by Techn1x** [comment]
Crosslinking this issue https://github.com/ember-cli-deploy/ember-cli-deploy-s3/issues/177 - hoping that this v3 update will fix/support creds specified via `~/.aws/config` as well..

This is probably highly relevant to that
https://github.com/aws/aws-sdk-js-v3/blob/main/UPGRADING.md#shared-credential-file-credentials

**Comment by Pixelik** [comment]
Hello 👋 

Is a PR for an upgrade to [aws-sdk-js-v3](https://github.com/aws/aws-sdk-js-v3) already in the works ?

**Comment by gzurbach** [comment]
@Pixelik I haven't had the opportunity to work on it unfortunately, the last few weeks have been very busy.

**Comment by Pixelik** [comment]
That's ok thank you @gzurbach I might also have a go at it if I find time even though I'm not familiar with the codebase 🙏

**Comment by DirkLachowski** [comment]
Anybody currently on this except https://github.com/ember-cli-deploy/ember-cli-deploy-s3/issues/173?
