### ISSUE TITLE
Release 5.0 out of beta?

### ISSUE THREAD

**Issue by gzurbach** [ember-cli-deploy/ember-cli-deploy-s3#191]
Hi there,

We've been successfully using `5.0.0-beta.0` in a fairly large project for a couple of months now, without issues. We're aware that at least one user reported issues with AWS SDK v3, but given the lack of progress in identifying the root cause of this issue, we find ourselves at an impasse.

Would it be possible to release 5.0.0 as a stable package for those who are able to use it without issues? 

It would also align `ember-cli-deploy-s3` and `ember-cli-deploy-s3-index` on the same AWS SDK version, which seems important.

Thank you for your consideration :)

**Comment by lukemelia** [comment]
[5.0.0](https://github.com/ember-cli-deploy/ember-cli-deploy-s3/releases/tag/v5.0.0) has been released.

**Comment by gzurbach** [comment]
Thanks @lukemelia !
