### ISSUE TITLE
Include Reasonable S3 CORS Defaults

### ISSUE THREAD

**Issue by lukemelia** [ember-cli-deploy/ember-cli-deploy-s3#22]
Moved from https://github.com/ember-cli/ember-cli-deploy/issues/103

We should add details to the README to help people configure the CORS support for hosting their assets on S3.

**Comment by robinvdvleuten** [comment]
Can you give a small example how to achieve this?

**Comment by ghedamat** [comment]
@robinvdvleuten 

something like this
https://gist.github.com/tmilewski/bfaebc876cc116623e86

is probably a decent starting point

you might be ok with allowing just GET requests as that's all you need for fonts
