### ISSUE TITLE
Support IAM Roles

### ISSUE THREAD

**Issue by ryansch** [ember-cli-deploy/ember-cli-deploy-s3#29]
This plugin should not require `accessKeyId` and `secretAccessKey` outright.  The default behavior of `aws-sdk` is to load temporary keys from an IAM Role if one exists.  Our deploy tooling runs `ember deploy production` on an instance running in our VPC with a role and as such should not require a static set of keys.

**Comment by ghedamat** [comment]
@ryansch do you think #39 will solve your use case?

**Comment by ryansch** [comment]
Yes!  Great work!
