### ISSUE TITLE
Support Riak S2

### ISSUE THREAD

**Issue by listepo** [ember-cli-deploy/ember-cli-deploy-s3#30]
Hi, there is a support Riak S2?

**Comment by LevelbossMike** [comment]
I don't have experience with Riak S2. As far as scanning through its docs though it seems that it should be compatible with the S3 api from Amazon though. It would be great if you could check if the options provided by ember-cli-deploy-s3 are enough to use it with Riak S2 (I suppose you have access to a Riak S2 installation). We'd be happy to include that in the docs.

**Comment by listepo** [comment]
@LevelbossMike You can also look http://docs.basho.com/riakcs/latest/riakcs-downloads/

**Comment by LevelbossMike** [comment]
It would be great if someone who actually uses Riak S2 and has a working installation could verify if this worked.

Closing for now. 

Feel free to reopen if this does not work as expected and configuration options to make this work are missing in this plugin.
