### ISSUE TITLE
what ever happened to the cloudFrontSubdomain key

### ISSUE THREAD

**Issue by danielspaniel** [ember-cli-deploy/ember-cli-deploy-s3#32]
There used to be an option to set cloudfront subdomain key 
      cloudFrontSubdomain: 'blahblah' 
 in the s3 options. Did that dissappear? .. does not seem to work anymore

**Comment by achambers** [comment]
Hi @danielspaniel. I _think_ you'll find that the old "adapter" passed the config object in as is, however in this new v0.5 plugin we explicitly pass in the options to the S3 client lib. (https://github.com/ember-cli-deploy/ember-cli-deploy-s3/blob/master/lib/s3.js#L17-L21)

This is the reason why you can no longer do it. It does seem strange that we don't allow a user to specify any number of other options that the S3 client lib accepts....Will chat this over with the team.

**Comment by lukemelia** [comment]
What did the `cloudFrontSubdomain` key do?

**Comment by danielspaniel** [comment]
Hmm .. yeah .. that is a fabulous question .. I am now seeing that it did not do much .. of anything. It turns out the action was in brocfile ( ember-cli-build ) 

```
 var cloudFrontUrl = 'make something here';
 var app = new EmberApp(defaults, {
    fingerprint: {
      enabled: isProductionLikeBuild,
      prepend: cloudFrontUrl
    },
```

so I think this is a non issue ..
