### ISSUE TITLE
How do I configure to upload a gzip instead of the assets

### ISSUE THREAD

**Issue by jrdn91** [ember-cli-deploy/ember-cli-deploy-s3#36]
I see it can use `ember-cli-deploy-gzip` and maybe I'm just not reading into it enough but what do I actually need to do to get this to upload the gzip file instead of the assets them selves?

I'm planning on using this with codedeploy to roll out these changes across an apache auto scaling group but codedeploy needs to listen on a zip or gzip file.

**Comment by lukemelia** [comment]
By default, the gzip plugin gzips in place, adds a list of gzipped files to the deploy context, and the S3 plugin deploys the files and sets the right header based on the list on the deploy context.

I'm not familiar with codedeploy.

**Comment by jrdn91** [comment]
All codedeploy is doing is watching for revisions on a single asset in an s3 bucket, at which point it will start a deployment process which copies the zip file, unzips it and places the files in a specified location on disk and then moves on to the next instance in the auto scaling group until the revision has been rolled to all servers.

So to make that work all I need to do is upload a single zip or gzip file. But after installing `ember-cli-deploy-gzip` all the assets are still being uploaded as apposed to what I assumed it would do which is one gzip'ed file.

**Comment by lukemelia** [comment]
Ah, I see. That is not what ember-cli-deploy.gzip does. It zips files in
place. I would be open to a config option for ember-cli-deploy-gzip to
create an archive, or you could create a new plugin called perhaps
"ember-cli-deploy-archive" to do this.

**Comment by jrdn91** [comment]
Yeah I thought about doing that, seems like it should be rather simple I would imagine.
