### ISSUE TITLE
Support for AWS Code Deploy

### ISSUE THREAD

**Issue by MojoJojo** [ember-cli-deploy/ember-cli-deploy-s3#38]
I'm not sure how other people use this plugin, but was wondering if it would be a good idea to add support for AWS code deploy in this module? 
In my current project, I'm looking at deploying to Amazon cloud and use code deploy to automatically deploy it on EC2 hosts. This s3 deploy plugin already has 80 - 90% of the functionality. The additional functionality that is required:
1. Add a flag to enable code deploy features. Perhaps a Boolean awsCodeDeploy option set via config.
2. If the flag is enabled, look for another option for app spec yml file (other wise default to appspec.yml) and if present, create an archive file and upload to S3.

Looking for ideas, comments and suggestions.

**Comment by lukemelia** [comment]
@MojoJojo I haven't used Code Deploy myself, but I'm open to this plugin gaining functionality that would make it easier to use with Code Deploy. I could also imagine a separate dedicated plugin for Code Deploy.

**Comment by MojoJojo** [comment]
@Lukemelia I started with adding functionality to your plugin but then separated it into a different plugin. The upload to S3 module is largely based on your code: 

https://github.com/MojoJojo/ember-cli-deploy-aws-codedeploy

Will clean up code and will add tests over next few days.

**Comment by ghedamat** [comment]
seems this can be closed then
