### ISSUE TITLE
Favicon.ico is not accessible at /

### ISSUE THREAD

**Issue by florent-blanvillain** [ember-cli-deploy/ember-cli-deploy-s3#47]
Hi,

How to prevent favicons and others from being uploaded to s3 ?
My goal is to have /favicon.ico accessible.

Config :

```
var config = {
  ...
  fingerprint: {
    enabled: true,
    prepend: "https://some-cloudfront-distribution",
    exclude: ['apple-touch-icon', 'favicon', 'mstile', 'android-chrome', 'browserconfig.xml', 'crossdomain.xml']
  },
  ...
};
```

**Comment by LevelbossMike** [comment]
I guess broccoli-asset-rev does not fingerprint `.ico` files by default. You have to add it to the `extensions`-array in the fingerprint options. Then your favicon should be fingerprinted correctly and should also have the cdn url prepended.

You can have a look at options for broccoli-asset-revs (the addon responsible for fingerprinting assets for a production build) here:

https://github.com/rickharrison/broccoli-asset-rev#options

After that it should be fine to upload your favicon to s3 and you can also update it, as it will be fingerprinted as any other asset.

**Comment by florent-blanvillain** [comment]
But would'nt it be better to let those assets be served by the main domain ?

**Comment by LevelbossMike** [comment]
Well that depends what kind of deployment flow you are using. In my case the ember app would be the main domain. Sorry I thought you were having trouble with the fingerprint settings.

If you want to exclude the ico file from the s3-upload you could just remove the file extension from the filePattern option for s3:

https://github.com/ember-cli-deploy/ember-cli-deploy-s3#filepattern

**Comment by florent-blanvillain** [comment]
If I exclude *.ico files, ember will just route /favicon.ico to /public/favicon.ico ?
The ember app is my main domain (as I understand it). See : provideup.com

**Comment by florent-blanvillain** [comment]
Sorry, as you can see I'm a little lost here :-) 
I think the problem is with my node server :-)

**Comment by LevelbossMike** [comment]
Ember won't redirect a request for your favicon. The user's browser will just load the favicon based on what's the path for the favicon in the bootstrap index.html that ember-cli creates for you when running `ember build`. So if you want to show a favicon with a different path as the default you can just change the path to the favicon in index.html and it should work. So just change the path in index.html in your app folder and don't add ico files to your broccoli-asset-rev settings and it should work as you want it to.

Hope that helps.

**Comment by florent-blanvillain** [comment]
You're right, indeed Ember has nothing to do with the routing of static ressources ! 
I think I will use my node server to proxy those ressources to /.
Thank you
