### ISSUE TITLE
Version 2.4.0 of aws-s3 client causing issues - SignatureDoesNotMatch

### ISSUE THREAD

**Issue by edslocombe** [ember-cli-deploy/ember-cli-deploy-s3#59]
I've finally got to the bottom of an issue I've been looking at for most of the day - locally my ember lightening fast deploy setup would upload to S3 fine. On our build server however I had a new error:

```
- SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
- SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
    at Request.extractError (/.../node_modules/ember-cli-deploy-lightning-pack/node_modules/ember-cli-deploy-s3/node_modules/aws-sdk/lib/services/s3.js:524:35)
```

I now understand that although locally my versions of _ember-cli-deploy-lightning-pack_ and _ember-cli-deploy-s3_ are the same as my build server's, the _ember-cli-deploy-s3/node_modules/aws-sdk_ version was different.

The build server was using version 2.4.0 and locally with version 2.3.19 - version 2.3.19 uploaded fine, version 2.4.0 did not.

Adding the following to my package.json resolved the issue:

`"aws-sdk": "2.3.19"`

I don't understand what is causing the error for me in the later version - I did try to inspect upload data and params and could not see anything wrong with the request as [suggested in this ST post](http://stackoverflow.com/questions/2777078/amazon-mws-request-signature-calculated-does-not-match-the-signature-provided).

Maybe if others experience, it's worth fixing the version to 2.3.19 or understand what changes are required.

**Comment by edslocombe** [comment]
I see the [2.4.0 tag was made 18 hours ago](https://github.com/aws/aws-sdk-js/commit/4f7751382529ed22ce06edcf6cb119ba3ca8bc1e) - maybe it's not just me who is going to encounter this issue.

**Comment by ghedamat** [comment]
@edslocombe seems bad, 

might simply be a bug in 2.4.0 or something else 

we might wanna lock https://github.com/ember-cli-deploy/ember-cli-deploy-s3/blob/master/package.json#L48 to 2.3.19 and cut a release of ember-cli-deploy-s3 if there's no easy way to fix

/cc @lukemelia @achambers

**Comment by ghedamat** [comment]
@edslocombe we decided to lock to the older version for now using the `~` we will release shortly

if you have time to figure out how to make it work with `2.4.X` it would be gladly appreciated but no pressure :) 

thanks in the meantime!
