### ISSUE TITLE
Batching file uploads

### ISSUE THREAD

**Issue by tomlagier** [ember-cli-deploy/ember-cli-deploy-s3#78]
This may be a needlessly specific use-case, in which case we are happy to create a fork, but I thought I would mention it here to gauge interest in a PR.

Our use case is deploying a large app to a dockerized [fake-s3](https://github.com/jubos/fake-s3) bucket. This plugin issues all uploads at once, which results in hundreds of simultaneous network requests - actual S3 can handle this just fine, but fake-S3 chokes and dies. Performing the uploads iteratively, or in batches, solves the issue. 

The proposed PR would pass a config flag toggling batched or all-at-once behavior. If you guys think that is a worthwhile addition to the plugin I will follow up with a PR.

**Comment by lukemelia** [comment]
@tomlagier we would be open to a PR that supported this, provided that there is not a dramatic increase in code complexity to add this feature.

**Comment by ghedamat** [comment]
looks like this was resolved!
