### ISSUE TITLE
Specifying a different endpoint for AWS

### ISSUE THREAD

**Issue by adregan** [ember-cli-deploy/ember-cli-deploy-s3#90]
Hello. I'm wondering if there is any desire for a PR to add a configuration option allowing you to specify a different endpoint to point the AWS SDK.

My situation is that I'm am developing a deployment script/pipeline locally using [minio](https://minio.io/) as a stand-in for AWS, so I need to specify a local url as my endpoint in the s3 [config options](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#constructor_details).

If there is any interest, I'd be happy to open a PR (it's a fairly simple [change](https://github.com/adregan/ember-cli-deploy-s3/commit/1605bab6a550c5903ea5dc10da5a3ae67ad76eea))

**Comment by adregan** [comment]
I took another look around at the options when I realized I would need to submit a similar PR to ember-cli-deploy-s3-index and found that I can produce a custom s3Client which has its endpoint set and it should work for other s3 plugins that have an s3Client option.

```js
if (deployTarget === 'test') {
  const AWS = require('aws-sdk');

  const s3Options = Object.assign({}, ENV.s3, {
    endpoint: 'http://127.0.0.1:9000'
  });

  ENV.s3.s3Client = new AWS.S3(s3Options);
}
```

Unless there is something I'm missing, I'm pretty content with this solution.

**Comment by jeffjewiss** [comment]
I'd be interested for you to open a PR with the change you linked to above.

Digital Ocean just released their Spaces product, which is S3 SDK compatible object storage. With the addition of being able to specify the endpoint, it should be pretty straightforward to use Digital Ocean as a deploy target.

Cheers!

**Comment by brunoocasali** [comment]
@adregan I've created a plugin: https://github.com/trustvox/ember-cli-deploy-minio to work with minio and it worked ;) 

If you could help me to improve, I'm accepting PR's ;D
