### ISSUE TITLE
Feature Request -- ability to upload a non-fingerprinted file even if present in s3

### ISSUE THREAD

**Issue by stephencattaneo** [ember-cli-deploy/ember-cli-deploy-s3#92]
I have a file that I need uploaded to s3 even if it is already present.  The content of the file is changing, but it is not fingerprinted. Since the file is fingerprinted, the file is listed in the manifest, and is present in s3, currently the file does not get uploaded.

I've already forked and added this feature, I can add a PR if this is a feature you'd like to see added to the mainline.

**Comment by achambers** [comment]
@stephencattaneo My preference would be to add a `fileIgnorePattern` config option to [ember-cli-deploy/ember-cli-deploy-manifest](https://github.com/ember-cli-deploy/ember-cli-deploy-manifest) which would allow you to describe the files that should not be added to the manifest and therefore, will always be uploaded.

An example of this is in the [ember-cli-deploy/ember-cli-deploy-gzip](https://github.com/ember-cli-deploy/ember-cli-deploy-gzip#ignorepattern)

**Comment by stephencattaneo** [comment]
I think I like your suggestion better. My change felt hacky.  I'll submit a PR to ember-cli-deploy-manifest
