### ISSUE TITLE
Using AWS credential profile

### ISSUE THREAD

**Issue by rynam0** [ember-cli-deploy/ember-cli-deploy-s3#95]
HI, great plugins!
I'm just getting started with ember-cli-deploy and am running into some issues in attempting to use the `profile` configuration.  I have an `.aws/credentials` file that contains 2 sets of credentials: one is `[default]` and the other is `[staging]`.  The docs led me to believe that I could simply omit `accessKeyId` and `secretAccesskey` and instead pass a `profile` configuration (`profile: 'staging'`).  When I go this route, the default credentials are used.  Is this a bug or am I simply misunderstanding how to use profiles?  

Thanks!

**Comment by achambers** [comment]
Hi @rynam0. Can you confirm the full path of the creds file? Is it `~/.aws/credentials`?

**Comment by rynam0** [comment]
Hey, @achambers. Thanks for the reply. Yes, my credentials file is in the standard location you specify. I also noticed that only the default profile seems to be used in the following cases:
- .env.deploy dot files are used instead of the profile config
- using profile config: default profile creds are used

If I rename the default profile I am then able to use the dot file configuration. Strange right?

**Comment by rynam0** [comment]
My mistake... sorry for the noise, everyone.
I removed all other `ember-cli-deploy` plugins and the profile configuration certainly works.
I think the issue is that `ember-cli-deploy-s3-index` doesn't support the profile configuration.
I'll look there next. Again, sorry for the noise.
